#server:
#  port: 8082
#  application:
#    name: sf-account-management-service
#logging:
#  file:
#    name: logs/sf-account-management-service.log
#
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#       auto-offset-reset: earliest
#       bootstrap-servers: localhost:9092
#       group-id: testgroup
#       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#       value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#       properties:
#         spring.json.trusted.packages: com.learning.events # change this with your event packages
#    producer:
#      acks: -1
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#  # Hibernate ddl auto (create, create-drop, update)
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create