services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - USERNAME=${USER_NAME}
      - PASSWORD=${PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - SECURITY_TOKEN=${SECURITY_TOKEN}
      - TOKEN_URL=${TOKEN_URL}
      - LOGGING_FILE_NAME=/logs/salesforce-account-management.log
    volumes:
      - log_volume:/logs
  splunk:
    image: splunk/splunk:8.0
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"
  splunkforwarder:
    image: splunk/universalforwarder:8.0
    hostname: splunkforwarder
    environment:
        - SPLUNK_START_ARGS=--accept-license --answer-yes
        - SPLUNK_STANDALONE_URL=splunk:9997
        - SPLUNK_USER=root
        - SPLUNK_ADD=monitor /logs
        - SPLUNK_PASSWORD=password
    restart: always
    depends_on:
      - splunk
    volumes:
        - log_volume:/logs
volumes:
  log_volume: